# Generated by Django 2.2 on 2020-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rec', '0002_student_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='BASE_DIRstatic/images/nobody.jpg', null=True, upload_to=''),
        ),
    ]
