# Generated by Django 2.2 on 2020-05-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_rec', '0004_auto_20200507_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='profile_pic',
            field=models.ImageField(default='static/images/nobody.jpg', upload_to=''),
        ),
    ]
